# Generated by Django 3.1.4 on 2020-12-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamunda', '0002_auto_20201215_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_type',
            field=models.CharField(choices=[('cereals', 'CEREALS'), ('livestock', 'LIVESTOCK'), ('vegetables', 'VEGETABLES'), ('tubers', 'TUBERS'), ('fisheries', 'FISHERIES'), ('poultry', 'POULTRY'), ('others', 'OTHERS')], default='others', max_length=50),
        ),
    ]
