# Generated by Django 3.1.4 on 2020-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamunda', '0004_auto_20201216_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='Kano', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(default='01-6547-5674', max_length=15),
        ),
    ]
