# Generated by Django 3.1.4 on 2020-12-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamunda', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
